# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_task_edit(object):
    def setupUi(self, Form_task_edit):
        Form_task_edit.setObjectName("Form_task_edit")
        Form_task_edit.resize(400, 132)
        Form_task_edit.setMinimumSize(QtCore.QSize(0, 132))
        Form_task_edit.setMaximumSize(QtCore.QSize(16777215, 132))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form_task_edit)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form_task_edit)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 114))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 114))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_cancel_edit = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cancel_edit.setObjectName("pushButton_cancel_edit")
        self.horizontalLayout_3.addWidget(self.pushButton_cancel_edit)
        self.pushButton_create = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout_3.addWidget(self.pushButton_create)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_task_edit = QtWidgets.QLabel(self.groupBox)
        self.label_task_edit.setObjectName("label_task_edit")
        self.verticalLayout.addWidget(self.label_task_edit)
        self.label_time_edit = QtWidgets.QLabel(self.groupBox)
        self.label_time_edit.setObjectName("label_time_edit")
        self.verticalLayout.addWidget(self.label_time_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_task = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_task.setObjectName("lineEdit_task")
        self.verticalLayout_2.addWidget(self.lineEdit_task)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_2.addWidget(self.dateTimeEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form_task_edit)
        QtCore.QMetaObject.connectSlotsByName(Form_task_edit)

    def retranslateUi(self, Form_task_edit):
        _translate = QtCore.QCoreApplication.translate
        Form_task_edit.setWindowTitle(_translate("Form_task_edit", "Изменить задачу"))
        self.groupBox.setTitle(_translate("Form_task_edit", "Изменить задачу"))
        self.pushButton_cancel_edit.setText(_translate("Form_task_edit", "Отменить"))
        self.pushButton_create.setText(_translate("Form_task_edit", "Ок"))
        self.label_task_edit.setText(_translate("Form_task_edit", "Описание задачи"))
        self.label_time_edit.setText(_translate("Form_task_edit", "Время"))
